apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: "eur1ap1rapidfeestk8-44a4"
    labels:
        app: "eur1ap1rapidfeestk8-44a4"
    annotations:
        kubernetes.io/ingress.class: addon-http-application-routing
spec:
    rules:
        - host: sparkie-eur1ap1rapidfeestk8-44a4.46546bbf8c4c48199dcc.westeurope.aksapp.io
          http:
            paths:
            - path: /
              backend:
                serviceName: "eur1ap1rapidfeestk8-44a4"
                servicePort: 80