apiVersion: v1
kind: Service
metadata:
    name: "eur1ap1rapidfeestk8-a7ea"
    labels:
        app: "eur1ap1rapidfeestk8-a7ea"
spec:
    type: ClusterIP
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "eur1ap1rapidfeestk8-a7ea"